### ISSUE TITLE
Support import from CSS

### ISSUE THREAD

**Issue by Smile4ever** [FirefoxBar/xStyle#12]
Currently you only support JSON when importing from file.

I would like to import CSS files (Mozilla style).

**Comment by sylingd** [comment]
You can only import from Mozilla format by-hand. The new `.user.css` format is planning

**Comment by Smile4ever** [comment]
Can you generate a name for a Mozilla style CSS file?
wikipedia-style-for-beginners.css => title = Wikipedia style for beginners

**Comment by sylingd** [comment]
Nice idea. I will add this feature next version

**Comment by sylingd** [comment]
Added in version 1.4.0

**Comment by svnpenn** [comment]
https://github.com/openstyles/stylus/issues/101

**Comment by svnpenn** [comment]
https://github.com/openstyles/stylus/pull/134

**Comment by svnpenn** [comment]
https://github.com/FirefoxBar/xStyle/issues/23
