### ISSUE TITLE
1.4.3繁體語系修正

### ISSUE THREAD

**Issue by zhtw2013** [FirefoxBar/xStyle#14]
[zh_TW.zip](https://github.com/FirefoxBar/xStyle/files/1227326/zh_TW.zip)

修正了1.4.3版zh-TW语系中不正确的繁体用语与漏翻的简体字。
另外，吧主有没有QQ号？ 我想要直接跟吧主交流....
有的话麻烦把QQ号寄到 zhtw2013{at}gmail.com 我会加你的！

**Comment by wenketel** [comment]
你可以在[transifex](https://www.transifex.com/sytec/xstyle)提交翻译

**Comment by sylingd** [comment]
请直接在[transifex](https://www.transifex.com/sytec/xstyle)提交翻译，下个版本会自动合并到代码库
