### ISSUE TITLE
能否同步样式？

### ISSUE THREAD

**Issue by ivysrono** [FirefoxBar/xStyle#15]
用 Firefox 自带的同步，或者像 Violentmonkey 那样，用 Dropbox/Onedrive/GoogleDrive/WebDav 等等。

**Comment by sylingd** [comment]
Firefox自带的同步限制100kb，根本无法同步样式。
Dropbox和WebDav可以考虑

**Comment by sylingd** [comment]
目前已经支持OneDrive和Google Drive

**Comment by ivysrono** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/stylishsync/
当年有这个扩展可以同步样式，利用Firefox自带的同步，不是很清楚原理是什么。

**Comment by sylingd** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/sync

**Comment by ivysrono** [comment]
我是说，不清楚 stylishsync 是怎么绕过 100k 的限制的。

**Comment by sylingd** [comment]
传统扩展权限很大
