### ISSUE TITLE
Gap after apostrophe

### ISSUE THREAD

**Issue by nyuszika7h** [FirefoxBar/xStyle#16]
I noticed a minor display issue: there's a gap after the apostrophe in "You don’t have any styles installed for this site.". Using Firefox Nightly 57.0a1.

![Screenshot](https://user-images.githubusercontent.com/482367/29498355-6ed3de8e-85fa-11e7-8f8e-f55480eab09e.png)

**Comment by sylingd** [comment]
Fixed
