### ISSUE TITLE
无法从userstyles安装样式

### ISSUE THREAD

**Issue by harytfw** [FirefoxBar/xStyle#17]
我尝试从userstyles处安装这个样式：https://userstyles.org/styles/100473/

点击 “Install style”后 ，弹出确定框，确定，接着页面卡住，没有反应。
过了一会浏览器上方出现提示信息 “某个网页让您的浏览器变慢了。您想如何处理？” ，后面还有两个按钮 “停止”和“等待”

点击“停止”，页面正常，样式没有成功安装，什么错误信息都没出现。
点击“等待”，页面依旧无反应，等一会后继续出现上面的提示信息

**Comment by sylingd** [comment]
已在最新提交中修复，请等待下一个新版本的发布
