### ISSUE TITLE
Color Picker problems

### ISSUE THREAD

**Issue by Mottie** [FirefoxBar/xStyle#18]
The color picker is being applied to css selectors:

![](https://user-images.githubusercontent.com/136959/29590439-70527f98-875f-11e7-8c9c-9df33b5b5a31.png)

and inside of comments:

![](https://user-images.githubusercontent.com/136959/29590548-fce32a3e-875f-11e7-9b38-0977ad376144.png)

**Comment by sylingd** [comment]
This is color picker's bug, please submit [here](https://github.com/easylogic/codemirror-colorpicker/issues)

**Comment by Mottie** [comment]
Done - https://github.com/easylogic/codemirror-colorpicker/issues/13

**Comment by sylingd** [comment]
I updated it to the latest version, this problem has been resolved.
Please waiting for the next release
