### ISSUE TITLE
当前网站生效计数不对

### ISSUE THREAD

**Issue by zhanxiage233** [FirefoxBar/xStyle#21]
RT ff55.0.3 win7x64 xstyle2.0.5

**Comment by sylingd** [comment]
请给出更详细的描述

**Comment by zhanxiage233** [comment]
举个例子吧 ，我总共安装了两个样式 cat520的字体和贴吧样式 ，在google+页面也显示两个生效样式

**Comment by sylingd** [comment]
@zhanxiage233 哪个贴吧样式？请给出链接，谢谢

**Comment by zhanxiage233** [comment]
https://userstyles.org/styles/124770/tieba-maverick

**Comment by sylingd** [comment]
无法复现问题。请尝试重新安装这两个样式，如果问题依旧，请导出**完整**备份后联系我
![2017-08-31_124148](https://user-images.githubusercontent.com/5326684/29906792-e96bfc24-8e49-11e7-9319-e7aee04217e3.png)

**Comment by zhanxiage233** [comment]
@sylingd 我可能找到问题出在哪了，这个贴吧样式的一个选项 Firefox兼容性补丁 选择之后，生效计数就不对

**Comment by sylingd** [comment]
此问题的原因，是样式作者有一行注释对全局生效了
