### ISSUE TITLE
Support external editors

### ISSUE THREAD

**Issue by svnpenn** [FirefoxBar/xStyle#22]
With Stylish, you can have a CSS like this:

~~~css
@import "file:C:/github.css";
@-moz-document url-prefix(http) {}
~~~

and it will allow styles to be read from external file.

**Comment by svnpenn** [comment]
https://github.com/openstyles/stylus/issues/86

**Comment by svnpenn** [comment]
https://github.com/openstyles/stylus/issues/91

**Comment by sylingd** [comment]
WebExtension have not permisson to access local file

**Comment by svnpenn** [comment]
:(
