### ISSUE TITLE
Import multiple CSS

### ISSUE THREAD

**Issue by svnpenn** [FirefoxBar/xStyle#23]
I keep a CSS for each site:

http://github.com/svnpenn/dotfiles/tree/72eaf5f/xstyle

so it would be nice to be able to import them all at once, instead of one at a
time

**Comment by svnpenn** [comment]
https://github.com/FirefoxBar/xStyle/issues/12

**Comment by sylingd** [comment]
I have added this feature to the latest commit.
Because the [AMO version](https://addons.mozilla.org/en-US/firefox/addon/xstyle/) is waiting for review, so I will release the new version at a later time, please understand, thanks.

**Comment by svnpenn** [comment]
thank you!

**Comment by sylingd** [comment]
I have released the new version, please update and test it.

**Comment by svnpenn** [comment]
works great! thanks again
