### ISSUE TITLE
Styles wont fully load on new tabs

### ISSUE THREAD

**Issue by JumpySWE** [FirefoxBar/xStyle#24]
When opening styled websites in a new tab, the installed style(s) will only partially apply. When visiting the new tab(s), I have to reload the page for it to be fully styled.

Here's a quick video showing what I mean: https://youtu.be/B5ZHpbUrzRQ

**Comment by sylingd** [comment]
I have tested in Firefox Nightly 57.0a1(2017-09-10) right now, it works well. Try to update your Firefox

**Comment by JumpySWE** [comment]
Tried it with latest Nightly just now and had the exact same problem, fresh install and profile, only add-on was xStyle.

**Comment by sylingd** [comment]
What is the style you used? Please give me a URL to install it or a export file

**Comment by JumpySWE** [comment]
In the video I used https://userstyles.org/styles/133277/reddit-no-frills-dark
But it's the same for pretty much every style I try/use, even my own.

**Comment by JumpySWE** [comment]
P.S. If you open a new tab and focus on it instantly, the style loads fine. It only acts like this when you open a new tab and let it load in the background, and then focusing on it when it's loaded.

**Comment by sylingd** [comment]
I have found the reason and I will fix this bug for a few days

**Comment by sylingd** [comment]
Fixed in [https://github.com/FirefoxBar/xStyle/commit/6081ef4191fb867344cf63deee12983a44eabd0c](https://github.com/FirefoxBar/xStyle/commit/6081ef4191fb867344cf63deee12983a44eabd0c).
The new version will be released in a few days.
