### ISSUE TITLE
xStyle主介面上無法管理樣式(樣式未出現)

### ISSUE THREAD

**Issue by shiloh0920** [FirefoxBar/xStyle#26]
作業系統版本：Win10 16278.rs3_release 170825-1441

Firefox版本：56.0b10 (64位元)

附加元件：
卡巴斯基防護 / Decentraleyes / Ghostery / h264ify / PTT-Web-Enhanced / Smart HTTPS /
smartUP手勢 / Tampermonkey / uBlock Origin / xStyle /

問題描述：
無法在xStyle主介面中管理樣式，沒有樣式出現(如附圖)
但在開啟選單那邊的小介面點xStyle時則可以看到當前網頁套用的樣式。
 有重新安裝過自分發已簽版本，還是無法看到樣式。
麻煩泷涯大和道滿大了，謝謝。
[附圖](http://i65.tinypic.com/33wp7wi.jpg  ) [附圖2](http://i64.tinypic.com/2e2midy.jpg)

**Comment by sylingd** [comment]
您好，请在管理界面按F12，查看Console里的错误信息。如果看不懂，请上传截图

**Comment by shiloh0920** [comment]
[Console截圖](http://i68.tinypic.com/35clzwo.jpg)

抱歉忘記這部份了

**Comment by sylingd** [comment]
大概猜到是哪的问题了，今晚尝试修复

**Comment by sylingd** [comment]
已经在Firefox 56.0b10和b11进行测试，但多次尝试未能复现问题。
根据截图推测应该是Firefox偶然出现的BUG，原因可能是未能成功载入背景页面。
此问题在Firefox for Android上经常出现，但是在PC端基本上不会出现。
