### ISSUE TITLE
修改文本阴影不起作用

### ISSUE THREAD

**Issue by prodigalsword** [FirefoxBar/xStyle#29]
域名：www.pcbeta.com
规则：* { text-shadow: 0 0 black !important; }
浏览器： Firefox 55.0.3 32bit
刷新网页可以看到短暂的效果，刷新完效果消失。

**Comment by sylingd** [comment]
这不是xstyle的BUG，pcbeta的JS会自动移除掉xstyle创建的style标签（可能不是针对xstyle，但是达到了这个效果）
