### ISSUE TITLE
有没有可能支持这个样式？

### ISSUE THREAD

**Issue by BurningRaptor** [FirefoxBar/xStyle#32]
https://userstyles.org/styles/96257/auto-hidden-minimal-scrollbars-for-firefox
WebExtension有权限做这类修改吗？

**Comment by yfdyh000** [comment]
可能是需要 https://bugzilla.mozilla.org/show_bug.cgi?id=77790

**Comment by sylingd** [comment]
需要GUI权限。目前没有，不清楚后续会不会开放
