### ISSUE TITLE
打开管理界面时火狐控制台有错误提示

### ISSUE THREAD

**Issue by gamekingv** [FirefoxBar/xStyle#34]
只要打开管理页面就会提示控制台就会有两条Error: Could not establish connection. Receiving end does not exist.的错误，并且会令其他WE扩展的内置页面打开时也出现同样的错误，我禁用了xstyle就不会有提示，虽然不会影响使用，但能否看看是什么原因造成的？Win10 x64 FF55.0.3 x64 xstyle 2.0.11

**Comment by sylingd** [comment]
原因是知道的。因为xStyle会尝试向每个页面都插入apply.js，此js会建立一个监听。每次出现设置改变等情况的时候，都会尝试向所有标签页发送通知。但向自己发送通知(即管理页面向管理页面)和向一些没有权限的页面发送通知(例如Firefox/Chrome的内置页面)，就会出现此错误。
之前有尝试修复，不过因为会引起其他问题，也就没有再尝试修复。

**Comment by gamekingv** [comment]
原来如此，明白了，不过不影响使用也不要紧，因为自己也有写一些小扩展所以就想了解一下原因，谢谢你的回复。
