### ISSUE TITLE
DB error on fresh install

### ISSUE THREAD

**Issue by dylmye** [FirefoxBar/xStyle#36]
Just installed today, and immediately I'm greeted by this:
![screenshot showing disabled buttons](https://user-images.githubusercontent.com/7024578/31070490-770b4fe0-a758-11e7-8275-d9b6875cf1e8.png)
Right-clicking and going to manage styles gives me this error:
![screenshot showing DB error](https://user-images.githubusercontent.com/7024578/31070514-90de1bb4-a758-11e7-8f6f-0ab6abeda016.png)
How can I fix this?

* Firefox version 57.0b3 (64-bit)    
* Windows 10

**Comment by sylingd** [comment]
Please try those methods: [DB Error](https://github.com/FirefoxBar/xStyle/wiki/DB-Error). Are they effective?

**Comment by dylmye** [comment]
Thank you, that works now.

I found another bug, should I make a new issue for it? The issue is that in firefox 57, placing xStyle in the dropdown section makes the xstyle popout unreadable:

1 - 
![screenshot showing xstyle in additional extensions menu](https://user-images.githubusercontent.com/7024578/31079425-88dec89e-a77d-11e7-8909-599bcf1c1f50.png)

2 - 
![screenshot showing xstyle popout window forced to scroll](https://user-images.githubusercontent.com/7024578/31079467-ab1cadcc-a77d-11e7-9d1c-2b5ae1fa1eb1.png)


It looks fine otherwise.

**Comment by zhtw2013** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402845

**Comment by dylmye** [comment]
谢谢 :)

**Comment by wenketel** [comment]
23
挺有名
