### ISSUE TITLE
修改后可以在 addons.mozilla.org 上生效

### ISSUE THREAD

**Issue by yfdyh000** [FirefoxBar/xStyle#37]
按 https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c24 的方法（无需重启），https://github.com/gluons/AMO-Add-to-Collection-Stylish 能够生效。
https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/
https://bugzilla.mozilla.org/show_bug.cgi?id=1406795

https://github.com/FirefoxBar/xStyle/blob/182090b9b3a910f45d6997e37fabbfd3ed0d0a2d/scripts/common.js#L79
能否检测注入成功/失败，或者加个选项。在选项上或者失败时提示这种修改步骤。

**Comment by sylingd** [comment]
我找了一下，似乎没找到有获取浏览器配置的API
因为这个判断函数不只是在注入的时候会使用，因此直接修改这个函数似乎也不行

**Comment by sylingd** [comment]
移除了此限制，但没办法提示用户
