### ISSUE TITLE
Please add my localization...

### ISSUE THREAD

**Issue by vanja-san** [FirefoxBar/xStyle#39]
I made a translation for your permission in Russian. Please add! [>>>LINK<<<](https://github.com/vanja-san/xStyle/tree/patch-1/_locales/ru)

**Comment by sylingd** [comment]
I have add it to [transifex](https://www.transifex.com/sytec/xstyle/), it will effective in the next release.
If you would like continue to help us in translation, you can join the transifex team.

**Comment by vanja-san** [comment]
I'm not against!

**Comment by vanja-san** [comment]
Is it better for me to spread the "corrections" of the translation here, or to create a new issue?

**Comment by vanja-san** [comment]
I joined the team. I will continue the translation on transifex.

**Comment by sylingd** [comment]
Thank you
