### ISSUE TITLE
"Fix read page JS object" breaks compatibility

### ISSUE THREAD

**Issue by 8qwe24657913** [FirefoxBar/xStyle#4]
https://github.com/FirefoxBar/xStyle/commit/0df342243bba33527922e73b1d3fc8c4c936a704 used `wrappedJSObject`, which is firefox only.
As a simple workaround for communication between isolated world and page script, we can just append an invisible element to the document and set `xstyle_xxx` as its attribute.

**Comment by sylingd** [comment]
Fixed
