### ISSUE TITLE
Problem with window...

### ISSUE THREAD

**Issue by vanja-san** [FirefoxBar/xStyle#40]
In Firefox Quantum 57-beta, there is a problem...

![2017-11-09_09-01-02](https://user-images.githubusercontent.com/7201687/32584771-a13e3132-c52c-11e7-823c-74a0ff9db11f.png)
**It should be like this (Using uBlock as an example):**

![2017-11-09_09-01-21](https://user-images.githubusercontent.com/7201687/32584787-b91c7ef8-c52c-11e7-9982-0021a5adaf61.png)

--------
![2017-11-09_09-04-34](https://user-images.githubusercontent.com/7201687/32584838-06b2de8c-c52d-11e7-88e2-4de98a61d40e.png)

**Comment by zhtw2013** [comment]
firefox bug 
![00112](https://user-images.githubusercontent.com/9501406/32585086-a76138c0-c536-11e7-9794-73f48f5bbec4.png)

**Comment by vanja-san** [comment]
I apologize. I hope they fix it. You can then close the question.

**Comment by sylingd** [comment]
It's Firefox's problem.
But there is no document about it, so no one knows why there is such a problem and how to solute it.
