### ISSUE TITLE
Material Design's header color, Compact View, and a tiny style-installing bug

### ISSUE THREAD

**Issue by Crystal-RainSlide** [FirefoxBar/xStyle#41]
1. The old sclool Material Design is great, but the header should be colorful anywhere.
And
can it be customized by users?
2.Material Design use too much space on low resolution devices. A Compact View option should be added.
3.I failed to install some of the userstyles on userstyle.org, and failed again in getting any clue... (Due to internet ?
If it's the bad internet status, maybe you can try to apply some redownload (when time out...when connection lost...) to enhance it, which... ...It can make this ex better, anyway~

**Comment by sylingd** [comment]
我看你的动态似乎是国人……我们还是用中文沟通吧……

**Comment by Crystal-RainSlide** [comment]
好啊，正好换好 iBus ，输入不上的问题没解决成，在这边输中文得复制粘贴，或用 Chrome 和 Chrome OS 的输入法拓展……
第一个是指点击拓展图标后的界面的Header，不应该是白色而是主题色的
第二个嘛……分Compact 和 Minimum 
![Minimum](https://user-images.githubusercontent.com/16851802/33084432-ef4a2b34-cf1c-11e7-97aa-74f52d662a06.png)
Minimum 像这样吧……
![image](https://user-images.githubusercontent.com/16851802/33087393-67e12f04-cf25-11e7-8e74-169f3080c270.png)
Compact 像这样
第三个则是忘记说了：装不了的样式有随机性……而且，很可能第二天就装上了。（不然起码能有 装不上的样式 这个 clue

**Comment by sylingd** [comment]
1.这方面我会好好想想，再决定怎么改
2.这主意不错
3.可否试试测试版有没有改善？测试版下载链接：https://eyun.baidu.com/s/3miMM3OG 密码：Styy （PS:测试版与正式版互相独立）

**Comment by Crystal-RainSlide** [comment]
这个每次都装不上（尚未尝试翻墙
https://userstyles.org/styles/138068/google-udscbt

**Comment by Crystal-RainSlide** [comment]
测试版在 Firefox 上没有问题~

**Comment by sylingd** [comment]
已经添加精简版界面
