### ISSUE TITLE
能否使所有的样式代码全都归到一个编辑框里

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/xStyle#42]
样式的页面匹配越多，需要的编辑框越多，导致要找一段代码时每个编辑框都得搜索一下，很麻烦，改成以前的Stylish那样就很好，不知道有没有可能实现？

**Comment by wu67** [comment]
exm？不是只有一个框？
![2017-11-11 11 23 14](https://user-images.githubusercontent.com/19976224/32690794-58ca42b2-c737-11e7-8057-a1509fa8f75c.png)

**Comment by sylingd** [comment]
哪种方式好似乎没有定论。我在想能不能找个方法调查一下用户的看法

**Comment by YandLiu** [comment]
@wu67 我指的是这种页面匹配多的话，需要的编辑框很多
![image](https://user-images.githubusercontent.com/26127104/32696388-b403e10e-c7b1-11e7-9f38-9f372476b679.png)

**Comment by sylingd** [comment]
我明白你的意思，不过实在是不确定哪种方式更好

**Comment by sylingd** [comment]
新计划为启用less支持，因此将会只有一个编辑框，此功能正在开发中
