### ISSUE TITLE
从 userstyles.org 安装比较大的样式会报“无响应脚本警告”

### ISSUE THREAD

**Issue by hcw** [FirefoxBar/xStyle#43]
比如 https://userstyles.org/styles/107188/square-weibo-prettify 这个

**Comment by sylingd** [comment]
I fell uncomfortable recently... I will take a look when I get better

**Comment by sylingd** [comment]
这几天不舒服……等我好点再看看……

**Comment by sylingd** [comment]
这几天不舒服……等我好点再看看……

**Comment by sylingd** [comment]
很抱歉出现了这个问题，将会于下个版本修复

**Comment by sylingd** [comment]
已在Dev分支修复，下个版本发布时间可能较迟，请稍作等待
