### ISSUE TITLE
Style does not apply.

### ISSUE THREAD

**Issue by vanja-san** [FirefoxBar/xStyle#44]
1. LINK - [Google - udscbt](https://userstyles.org/styles/138068/google-udscbt)
2. In the Stylish itself is applied well.
3. And by the way, can you change the pop-up window? Why not do it in Material Design?
- xStyles 2.1.1
- Firefoxe 57

![2017-11](https://user-images.githubusercontent.com/7201687/32758103-49a5a904-c915-11e7-99cc-d92f901c1aef.gif)

**Comment by vanja-san** [comment]
And by the way, can you change the pop-up window? Why not do it in Material Design?

**Comment by sylingd** [comment]
I'm sorry for this problem, it will be fixed in the next version
