### ISSUE TITLE
After installing from userstyles, the advanced options do not work

### ISSUE THREAD

**Issue by hcw** [FirefoxBar/xStyle#49]
> for example:

Install some style from userstyles,
There is an advanced option in userstyles which is drop-down box, the default value of A, selected B, and then installed.
In xStyle, open the advanced options, the value displayed is B, **BUT** in effect it is A.
Then I modify it to A, save it, and then change it to B again, save it, then B will take effect.

---

### 从 userstyles 安装之后，高级选项不生效的问题

> 举个例子：

从 userstyles 安装某样式，userstyles 里高级选项有一项是下拉框，默认值A，选择了B，安装。
到 xStyle 里边，打开高级选项，显示的是 B，但实际上生效的是 A。
在 xStyle 里边，修改成 A ，保存，再次修改成 B，保存，这时 B 才能生效。

**Comment by sylingd** [comment]
已经修复，谢谢反馈
