### ISSUE TITLE
@document can only get the part of css from firefox stylish

### ISSUE THREAD

**Issue by 0w0miki** [FirefoxBar/xStyle#5]
I imported from xml to xStyle follow the instruction. All styles are imported, but none is effective.
From the editing interface, only the first domain matching.
Such as the following effective css in stylish
```css
@-moz-document domain("www.baidu.com"), domain("www1.baidu.com") {
```
in xStyle
```css
, domain("www1.baidu.com") {
```
This is an error here. The application object does not recognize the `www1.baidu.com` domain, and correspondingly `xStyle.json` file shows
```
{"sections":[{"urls":[],"urlPrefixes":["http://baidu.com"],"domains":[],"regexps":[],"code":", url-prefix(\"http://www.baidu.com\"), url-prefix(\
```
You can also see that only the first scope is extracted.
My xStyle version is 1.3.1 and Firefox version is 54.0.

---

我跟着说明从火狐stylish导入到xStyle 所有样式都导入了 但是都没有效果
从编辑界面看 只有第一个应用对象匹配上了
比如stylish下面有效的css
```css
@-moz-document domain("www.baidu.com"), domain("www1.baidu.com") {
```
在xStyle下
```css
, domain("www1.baidu.com") {
```
这段报错 应用对象那里没有识别`www1.baidu.com`域，`xStyle.json`文件对应
```
{"sections":[{"urls":[],"urlPrefixes":["http://baidu.com"],"domains":[],"regexps":[],"code":", url-prefix(\"http://www.baidu.com\"), url-prefix(\
```
也可以看到只提取出了第一个作用域
xStyle版本1.3.1 火狐版本54.0

**Comment by sylingd** [comment]
是使用stylish.team.firefoxcn.net进行的导出吗？
如果是，可否将您的stylish.sqlite发送至我的邮箱？
896640547@qq.com

**Comment by sylingd** [comment]
已经尝试了一些修复，请稍等一下再尝试一次

**Comment by 0w0miki** [comment]
可以了(｀・ω・´)
