### ISSUE TITLE
无法编辑已安装样式

### ISSUE THREAD

**Issue by atauzki** [FirefoxBar/xStyle#50]
安装一个样式之后，点击“编辑”跳到编辑样式界面，一直转圈

**Comment by wu67** [comment]
Mac 平台最新稳定版chrome和firefox都无法复现

**Comment by sylingd** [comment]
是否尝试Wiki中，3.0.0更新日志提供的解决办法？

**Comment by atauzki** [comment]
也许是我以前导入样式时出了问题，现在重新导入一遍就行了
