### ISSUE TITLE
以Wiki中提到的第三种方法安装样式会一直卡在请稍候界面

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/xStyle#51]
比如安装https://ext.firefoxcn.net/xstyle/install/open.html?code=https://raw.githubusercontent.com/gluons/AMO-Add-to-Collection-Stylish/master/AMO-Add-to-Collection.css
已用全新配置测试。

**Comment by sylingd** [comment]
已修复

**Comment by YandLiu** [comment]
3.0.2版本用空白配置又测试了一下，还是不行…… 浏览器控制台中报ReferenceError: t is not defined
![image](https://user-images.githubusercontent.com/26127104/34025918-899b90a6-e18d-11e7-92bb-16262d815fcf.png)

**Comment by sylingd** [comment]
已经重新确认，并且增加了对传统CSS文件的兼容性
