### ISSUE TITLE
Some Polish sentences are longer and because of that they don't fit in the line.

### ISSUE THREAD

**Issue by pabli24** [FirefoxBar/xStyle#52]
Screen:
![xstyle](https://user-images.githubusercontent.com/22481052/34260300-ae13d240-e665-11e7-9d03-379f99ed1384.png)

**Comment by sylingd** [comment]
Thanks for the feedback

**Comment by pabli24** [comment]
I see still not everything fits 
![](https://i.imgur.com/hrBchVD.png)
