### ISSUE TITLE
Add-on location permissions?

### ISSUE THREAD

**Issue by JumpySWE** [FirefoxBar/xStyle#54]
Firefox just notified me that there was an update available for xStyle (3.0.3) but that it required new permissions.

Why does xStyle require location permissions linked to gitee.io?

**Comment by sylingd** [comment]
gitee.io is a website like GitHub, see [here](https://github.com/FirefoxBar/xStyle/wiki/Install-styles-from-other-sites)

**Comment by JumpySWE** [comment]
But why does xStyle require geolocation permissions?

**Comment by sylingd** [comment]
I don't remember I used that permission. Where did you see it?

**Comment by JumpySWE** [comment]
When the add-on was updated in Firefox.

Firefox showed a new permissions pop-up for the xStyle (3.0.3) update.

**Comment by sylingd** [comment]
I have reviewed my code, I haven't change permissions in version 3.0.3 (In addition to the gitee domain name change in [this commit](https://github.com/FirefoxBar/xStyle/commit/0b77eadf581559fb22324fa4d06db91008ee82ed)), and I haven't write any code about geolocation permissions

**Comment by JumpySWE** [comment]
Hmm, this is wired then.
When I tried installing the 3.0.3 xpi directly, it showed the normal permissions.

But when Firefox automatically updated the add-on it asked for location permissions with a link to gitee.io

Perhaps I misread the pop-up.

I'll double check after the holidays since I won't have access to a computer until then (writing on phone now).

**Comment by sylingd** [comment]
If you find the reason, please tell me, thank you

**Comment by JumpySWE** [comment]
It was nothing... Just the Swedish translation of Firefox that made the pop-up a bit confusing to read quickly.
