### ISSUE TITLE
Math preprocessing bug

### ISSUE THREAD

**Issue by PalmtopTiger** [FirefoxBar/xStyle#56]
`height: calc(100vh - 43px);`
turns into
`height: calc(57vh);`
what is not the same.

**Comment by sylingd** [comment]
You can use calc(~"100vh - 43px") to solute this problem now.
I will confirm which component caused the problem later and submit this bug to its author

**Comment by sylingd** [comment]
I have found a issue related to this problem: https://github.com/less/less.js/issues/1366
In short, calc is a keyword of less, less will calculate it. But many values can not be calculated, for example, 100% - 10px, 100vh + 3px, but less aslo will try to calculate it. So, if you do not want less compiler calculate it:
If you do not use less variables in calc, use calc(~"100% - 40px")
If you want to use less variable in calc, use calc(~"100% - @{foo}")

**Comment by sylingd** [comment]
I will enable "Strict Math" option next version

**Comment by PalmtopTiger** [comment]
Thank you.
