### ISSUE TITLE
不知道是不是bug的问题

### ISSUE THREAD

**Issue by a1018148046** [FirefoxBar/xStyle#57]
https://www.bilibili.com/bangumi/play/ep86707
b站的番剧页面是嵌入的iframe 点击播放器的下一话后 本来生效的规则失去了作用

**Comment by sylingd** [comment]
我测试一切正常，你使用的哪个样式？能否提供样式内容？
![xx](https://user-images.githubusercontent.com/5326684/34467389-1b2d919a-ef2b-11e7-90cc-0c2bf7b309e8.gif)

**Comment by a1018148046** [comment]
`@-moz-document regexp("https?://www.bilibili.com/video/av\\d+?.+"), regexp("https?://www.bilibili.com/blackboard/html5player.html\\?.+") {
.bilibili-player.mode-widescreen:not(.mode-miniscreen) .bilibili-player-video-sendbar,
  .bilibili-player.mode-webfullscreen:not(.mode-miniscreen) .bilibili-player-video-sendbar{
    display:none!important;
  }
  .bilibili-player.mode-widescreen:not(.mode-miniscreen) .bilibili-player-video-wrap{
    height: calc(~"100% - 30px")!important;
  }
  .bilibili-player.mode-webfullscreen:not(.mode-miniscreen) .bilibili-player-video-wrap{
    height: calc(~"100% - 30px")!important;
  }
/*.bilibili-player.mode-webfullscreen .bilibili-player-video-control{
    opacity:0!important;
    position:absolute!important;
    bottom:0!important;
    transition:.5s;
}
.bilibili-player.mode-webfullscreen .bilibili-player-video-control:hover{
    opacity:1!important;
}*/
}`

**Comment by a1018148046** [comment]
点击播放器的下一话按钮
