### ISSUE TITLE
样式标题换行问题

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/xStyle#6]
可以让这种标题自动换行吗？
![2017-08-05_174715](https://user-images.githubusercontent.com/26127104/28994664-7e4ff118-7a06-11e7-83ef-ec30c2e82189.png)

**Comment by sylingd** [comment]
自动换行可能不大合适。下个版本会尝试让过长的标题只显示一部分

**Comment by wenketel** [comment]
那就应该加一个鼠标悬停显示全名

**Comment by sylingd** [comment]
@wenketel 嗯，可以

**Comment by sylingd** [comment]
Fixed
