### ISSUE TITLE
Cause conflict with another extension.

### ISSUE THREAD

**Issue by mikhoul** [FirefoxBar/xStyle#62]
It cause a conflict with another extension "[Panel View for Google™ Translate](https://chrome.google.com/webstore/detail/panel-view-for-google-tra/bcefgmhpbmghjcenbklchobmogjhaagl?utm_source=chrome-app-launcher-info-dialog)"

Here's the error:

![GitHub Logo](https://i.imgur.com/2Ifxv6b.png)

Regards :octocat:

**Comment by sylingd** [comment]
Please disable "Modify CSP header" in option
