### ISSUE TITLE
Firefox 首次访问 Userstyle.org 上任意样式时安装按钮不会显示，而是显示 Install with Stylish

### ISSUE THREAD

**Issue by Crystal-RainSlide** [FirefoxBar/xStyle#65]
RT

**Comment by sylingd** [comment]
请更新至最新版（3.0.8）
![tim 20180725231724](https://user-images.githubusercontent.com/5326684/43210199-04c68416-9061-11e8-9b27-5d8151f7fa7e.png)

**Comment by sylingd** [comment]
发现Firefox下少了一段代码，请等待下一个版本修复

**Comment by Crystal-RainSlide** [comment]
这得上 Travis CI 自动分流打包啊（x

**Comment by benzBrake** [comment]
> 
> 
> 发现Firefox下少了一段代码，请等待下一个版本修复

最近的FF版本又不显示了
