### ISSUE TITLE
xStyle被chrome扩展商店下架了？

### ISSUE THREAD

**Issue by suheandzl** [FirefoxBar/xStyle#79]
今天看到xStyle在chrome应用商店下架了，不知道是被下架还是作者主动下架。请问以后有重新上架的计划吗？

**Comment by sylingd** [comment]
因为描述不符合Google规范被下架，稍后会尝试重新提交

![QQ截图20210505144445](https://user-images.githubusercontent.com/5326684/117105393-80b30f80-adb0-11eb-8c85-99f67b070713.jpg)

**Comment by suheandzl** [comment]
好的 感谢回复 静待重新上架

**Comment by sylingd** [comment]
经过沟通，已经重新上架
