### ISSUE TITLE
1个bug，2个feature requests

### ISSUE THREAD

**Issue by YandLiu** [FirefoxBar/xStyle#8]
1. 点击工具栏图标展开的面板里下面两个按钮并没有始终固定在最底部
64位Firefox 55.0 （54也有这问题）
Windows 7，DPI放大至125%
如图所示：
![screenrecording](https://user-images.githubusercontent.com/26127104/29101499-360d558a-7ce5-11e7-8233-49af6681dae2.gif)

2. 是否可以支持在AMO上使用？有个很有用的AMO相关的样式
https://userstyles.org/styles/127380/amo-bring-back-favorites-and-collections

3. 可否像Stylish那样支持从URL安装样式？这样方便安装很多不在userstyles.org上放的样式

**Comment by sylingd** [comment]
1.收到。
2.我没有特地排除过AMO。如果在AMO上无效，可能是Firefox本身做了限制。
3.可以。详情请查看wiki

**Comment by sylingd** [comment]
第一个问题在1.3.4版本已修复
第二个问题，再次确认，是因为Firefox的限制。同样的代码在Chrome下，对AMO是有效的

**Comment by wenketel** [comment]
火狐的限制，about页面应该也是不能应用样式了。
参考 https://www.firefox.net.cn/3g-read-run?tid=54305&fid=5
