### ISSUE TITLE
this extension has been marked as unsafe in chrome webstore; 扩展被chrome store标记为不安全

### ISSUE THREAD

**Issue by TTTPOB** [FirefoxBar/xStyle#80]
![image](https://user-images.githubusercontent.com/19909103/117104344-8d366880-adae-11eb-9f13-56542d5bf11b.png)
and click the install link in repo readme lead you to a 404 page
点击项目readme上的网址也返回404页面

the browser is microsoft edge (based on chromium)

**Comment by sylingd** [comment]
因为描述不符合Google规范被下架，稍后会尝试重新提交

![QQ截图20210505144445](https://user-images.githubusercontent.com/5326684/117105393-80b30f80-adb0-11eb-8c85-99f67b070713.jpg)

**Comment by TTTPOB** [comment]
好的，谢谢您的回复

**Comment by sylingd** [comment]
经过沟通，已经重新上架
