### ISSUE TITLE
样式自定义设置安装无效是哪里的问题？

### ISSUE THREAD

**Issue by laincat** [FirefoxBar/xStyle#9]
https://userstyles.org/styles/100473/004-forcemyfonts-chinese-firefoxchromeie-catcat520

主要是用这个样式，发现怎么设置修改后，安装还是原来没设置的。。。

**Comment by sylingd** [comment]
此问题是由于旧版Stylish（即xStyle所基于的版本）不支持自定义设置所致
下个版本会尝试增加此功能

**Comment by sylingd** [comment]
已经在master中增加此功能，请等待其他问题修复完成后推送新版本

**Comment by sylingd** [comment]
已在1.4.0版本中修复
